### ISSUE TITLE
DOCKER_MACHINE_IP should be localhost?:

### ISSUE THREAD

**Issue by nicain** [testdrivenio/testdriven-site#10]
On https://testdriven.io/part-one-docker-config

https://github.com/testdrivenio/testdriven-site/blob/2550d46aa7c594676f25ee2289d38a0cb58f4658/part-one-docker-config.html#L1163

doesn't work for me.

```
docker-compose -f docker-compose-dev.yml ps
Name               Command               State           Ports
-----------------------------------------------------------------------
users   /bin/sh -c python manage.p ...   Up      0.0.0.0:5001->5000/tcp
```

Instead, changing

> Navigate to http://DOCKER_MACHINE_IP:5001/users/ping. Make sure you see the same JSON response as before. Next, add an environment variable to the docker-compose-dev.yml file to load the app config for the dev environment:

to:

> Navigate to http://localhost:5001/users/ping. Make sure you see the same JSON response as before. Next, add an environment variable to the docker-compose-dev.yml file to load the app config for the dev environment:

works

**Comment by nicain** [comment]
Weird; the address from `docker-machine ip` does not match the ip address returned from ifconfig:

```
[nicholasc@nicholasc-ubuntu]~/projects/reference_space/$ifconfig | grep -A 6 -B 1 192.168
vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00
          inet addr:192.168.99.1  Bcast:192.168.99.255  Mask:255.255.255.0
          inet6 addr: fe80::800:27ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:432 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:161115 (161.1 KB)

[nicholasc@nicholasc-ubuntu]~/projects/reference_space/$docker-machine ip reference-space-dev
**192.168.99.100**
```

When I pull up http://192.168.99.1:5001/users/ping, I get the "pong!" success message back from the flask endpoint.  Any idea why this would be the case?

**Comment by mjhea0** [comment]
`DOCKER_MACHINE_IP` is the IP associated with the machine. Run `docker-machine ip MACHINE_NAME` to get it.
