### ISSUE TITLE
Rearrange Dockerfile-prod to avoid re-running `npm install` when environment variables change

### ISSUE THREAD

**Issue by maxalbert** [testdrivenio/testdriven-site#14]
In [Part 2, Lesson 8](https://testdriven.io/part-two-react-and-docker) the `Dockerfile-prod` looks as follows:
```
# build environment
FROM node:9.4 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ARG REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.0 -g --silent
COPY . /usr/src/app
RUN npm run build

# production environment
FROM nginx:1.13.5-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

I was experimenting with the effect of changing the variable `REACT_APP_USERS_SERVICE_URL`. However, when rebuilding the docker image this meant that docker could not cache any of the layers after this variable is set. In particular, the commands
```
npm install --silent
npm install react-scripts@1.1.0 -g --silent
```
are run every time during a re-build, which is both time-consuming and results in unnecessary disk usage due to the extra layers being generated.

Suggestion: rearrange the file as follows.
```
# build environment
FROM node:9.4 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.0 -g --silent
ARG REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL
COPY . /usr/src/app
RUN npm run build

# production environment
FROM nginx:1.13.5-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```
This way the re-build of the image is much quicker and avoids the re-installation of lots of npm packages.

**Comment by mjhea0** [comment]
Yup. When a layer changes, all subsequent layers are re-built. Planning a big update on the course next month. I'll take all of your issues into account.

**Comment by maxalbert** [comment]
Sounds great, thanks!
