### ISSUE TITLE
Deployment Part 1, Lesson 10: can't reach http://DOCKER_MACHINE_IP:5001/users

### ISSUE THREAD

**Issue by yerrochdi** [testdrivenio/testdriven-site#22]
hello,

thank you for courses i have some pb during deployment section.
when check  docker-machine ls i saw my docker machine runing without error.
i add port 5001 in AWS Security Group 

![image](https://user-images.githubusercontent.com/22411555/46681608-e2f10700-cbeb-11e8-9f7b-1213bb6a3f47.png)

But when i test http://DOCKER_MACHINE_IP:5001/users/ping  nothing is happening and i have timeout error on the browser (DOCKER_MACHINE_IP getting with docker-machine ip testdriven-prod). 

thanks for your help and sorry for my english :)

**Comment by mjhea0** [comment]
Make sure you add that port to the AWS Security Group. http://stackoverflow.com/questions/26338301/ec2-how-to-add-port-8080-in-security-group

Also, if you have any more questions please email me - michael at mherman dot org. Thanks!
